--Temporary local data structure uses H2 database
DROP SCHEMA IF EXISTS MS_TASKS;
CREATE SCHEMA MS_TASKS AUTHORIZATION sa;
CREATE SEQUENCE MS_TASKS.TASKS_SEQ;
CREATE TABLE MS_TASKS.TASKS (
   id bigint default MS_TASKS.TASKS_SEQ.nextval PRIMARY KEY,
   taskId VARCHAR(50) NOT NULL,
   duration BIGINT NOT NULL
);
CREATE TABLE MS_TASKS.AVERAGE (
   taskId VARCHAR(50) NOT NULL,
   average DOUBLE NOT NULL
);
