#!/bin/bash

# Initialize MySQL database.
# ADD this file into the container via Dockerfile.
# Assuming you specify a VOLUME ["/var/lib/mysql"] or `-v /var/lib/mysql` on the `docker run` command…
# Once built, do e.g. `docker run your_image /path/to/docker-mysql-initialize.sh`
# Again, make sure MySQL is persisting data outside the container for this to have any effect.

set -e
set -x

rm -f /docker-entrypoint-initdb.d/databases-all.sql
mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /docker-entrypoint-initdb.d/databases-all.sql